apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::781195020338:role/eksctl-amazon-clone-nodegroup-amaz-NodeInstanceRole-GoCXgXXYvIjz
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - amazon-trainee
      userarn: arn:aws:iam::781195020338:user/suresh
      username: suresh
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-15T05:17:28Z"
  name: aws-auth
  namespace: kube-system
  uid: 8ed3650b-0397-43d0-849b-7027d30d8586
