apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: amazon
  name: amazon-trainee
rules:
  - apiGroups: [""] # "" indicates the core API group by default it is v1
    resources: ["pods"]  # nouns
    verbs: ["get", "watch", "list"]  # verbs

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: amazon
  name: amazon-junior
rules:
  - apiGroups: [""] # "" indicates the core API group by default it is v1
    resources: ["pods"]  # nouns
    verbs: ["get", "watch", "list"]  # verbs

  - apiGroups: ["apps"] # "" indicates the core API group by default it is v1
    resources: ["deployments"]  # nouns
    verbs: ["get", "watch", "list","create","update","patch","delete"]  # verbs

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: amazon
  name: amazon-lead
rules:
  - apiGroups: ["*"] # "" indicates the core API group by default it is v1
    resources: ["*"]  # nouns
    verbs: ["*"]  # verbs
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: suresh
  namespace: amazon
subjects:
  - kind: User
    name: suresh
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: amazon-lead
  apiGroup: rbac.authorization.k8s.io